In [1]:
import numpy as np

- 数据生成

In [2]:
point_A=np.random.randint(0,101,size=[5,2])
point_B=np.random.randint(0,101,size=[8,2])

- 距离矩阵计算

In [3]:
diff=point_A[:,np.newaxis,:] - point_B[np.newaxis,:,:]

In [4]:
distance_matrix=np.sqrt(np.sum(diff**2, axis=2))


In [5]:
distance_matrix

array([[19.41648784, 46.04345773, 74.27651042, 53.74011537, 85.0940656 ,
        78.81624198, 33.83784863, 48.76474136],
       [63.63961031, 39.        , 51.4003891 , 50.60632372, 85.42833254,
        37.58989226, 50.03998401, 76.92203845],
       [58.00862005, 44.72135955, 21.9317122 , 28.        , 55.97320788,
         8.24621125, 43.41658669, 53.75872022],
       [74.72616677, 78.31347266, 25.05992817, 38.01315562, 10.77032961,
        39.05124838, 65.37583651, 38.94868419],
       [56.56854249, 47.80167361, 12.80624847, 21.84032967, 46.86149806,
         5.38516481, 42.63801121, 46.09772229]])

- 轴向数据聚合

In [6]:
np.min(distance_matrix,axis=1)

array([19.41648784, 37.58989226,  8.24621125, 10.77032961,  5.38516481])

- 复合条件查询

In [7]:
np.where(np.any(distance_matrix.T<20,axis=1))

(array([0, 2, 4, 5]),)